import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Search, Trash2, ArrowLeft } from 'lucide-react';
import { CATEGORIES } from '../types';
import { formatCurrency, formatDate, groupExpensesByDate } from '../utils/helpers';
import { WatercolorCard } from './WatercolorCard';
import { EmptyState } from './EmptyState';
import { BotanicalDivider } from './BotanicalDivider';
export const ExpenseHistory = ({ expenses, onDelete, onBack }) => {
    const [searchTerm, setSearchTerm] = useState('');
    const [selectedCategory, setSelectedCategory] = useState('all');
    const filteredExpenses = useMemo(() => {
        return expenses.filter((expense) => {
            const matchesSearch = expense.note.toLowerCase().includes(searchTerm.toLowerCase());
            const matchesCategory = selectedCategory === 'all' || expense.category === selectedCategory;
            return matchesSearch && matchesCategory;
        });
    }, [expenses, searchTerm, selectedCategory]);
    const groupedExpenses = useMemo(() => groupExpensesByDate(filteredExpenses), [filteredExpenses]);
    const sortedDates = useMemo(() => Object.keys(groupedExpenses).sort((a, b) => new Date(b).getTime() - new Date(a).getTime()), [groupedExpenses]);
    return (_jsx("div", { className: "min-h-screen bg-cream bg-parchment px-4 py-8", children: _jsxs("div", { className: "max-w-4xl mx-auto", children: [_jsxs(motion.button, { onClick: onBack, initial: { opacity: 0, x: -20 }, animate: { opacity: 1, x: 0 }, whileHover: { x: -5 }, className: "flex items-center gap-2 text-forest/70 hover:text-forest mb-6 font-serif", children: [_jsx(ArrowLeft, { size: 20 }), "Back to Dashboard"] }), _jsxs(motion.div, { initial: { opacity: 0, y: -20 }, animate: { opacity: 1, y: 0 }, className: "text-center mb-8", children: [_jsx("h1", { className: "font-display-italic text-4xl text-rose mb-2", children: "Expense Chronicle" }), _jsx("p", { className: "font-serif text-forest/60", children: "Your journey through spending" })] }), _jsx(WatercolorCard, { delay: 0.2, className: "mb-6", children: _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "relative", children: [_jsx(Search, { className: "absolute left-4 top-1/2 -translate-y-1/2 text-forest/40", size: 20 }), _jsx("input", { type: "text", value: searchTerm, onChange: (e) => setSearchTerm(e.target.value), placeholder: "Search your tales...", className: "w-full pl-12 pr-6 py-3 bg-cream border-2 border-sage/20 rounded-2xl font-serif text-forest focus:outline-none focus:border-rose/40 transition-colors" })] }), _jsxs("div", { className: "flex flex-wrap gap-2", children: [_jsx(motion.button, { whileHover: { scale: 1.05 }, whileTap: { scale: 0.95 }, onClick: () => setSelectedCategory('all'), className: `px-4 py-2 rounded-full font-serif text-sm transition-all ${selectedCategory === 'all'
                                            ? 'bg-gradient-to-r from-rose to-mauve text-cream shadow-watercolor-sm'
                                            : 'bg-cream text-forest/70 border border-sage/20 hover:border-sage/40'}`, children: "All" }), Object.keys(CATEGORIES).map((cat) => (_jsxs(motion.button, { whileHover: { scale: 1.05 }, whileTap: { scale: 0.95 }, onClick: () => setSelectedCategory(cat), className: `px-4 py-2 rounded-full font-serif text-sm transition-all flex items-center gap-2 ${selectedCategory === cat
                                            ? 'bg-gradient-to-r from-rose to-mauve text-cream shadow-watercolor-sm'
                                            : 'bg-cream text-forest/70 border border-sage/20 hover:border-sage/40'}`, children: [_jsx("span", { children: CATEGORIES[cat].icon }), CATEGORIES[cat].name] }, cat)))] })] }) }), sortedDates.length > 0 ? (_jsx("div", { className: "space-y-6", children: sortedDates.map((date, dateIndex) => (_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { delay: 0.3 + dateIndex * 0.1 }, children: [_jsxs("div", { className: "flex items-center gap-4 mb-4", children: [_jsx("div", { className: "flex-1 h-px bg-gradient-to-r from-transparent via-sage/30 to-transparent" }), _jsx("p", { className: "font-serif text-forest/60 text-sm", children: formatDate(date) }), _jsx("div", { className: "flex-1 h-px bg-gradient-to-r from-transparent via-sage/30 to-transparent" })] }), _jsx("div", { className: "space-y-3", children: _jsx(AnimatePresence, { mode: "popLayout", children: groupedExpenses[date].map((expense, expIndex) => (_jsx(motion.div, { layout: true, initial: { opacity: 0, scale: 0.9 }, animate: { opacity: 1, scale: 1 }, exit: { opacity: 0, scale: 0.9, x: -100 }, transition: { delay: expIndex * 0.05 }, className: "bg-parchment p-4 rounded-2xl border-2 border-sage/10 hover:border-rose/20 hover:shadow-watercolor-sm transition-all group", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-4 flex-1", children: [_jsx("div", { className: "text-3xl", children: CATEGORIES[expense.category].icon }), _jsxs("div", { className: "flex-1", children: [_jsx("p", { className: "font-serif text-forest font-medium", children: expense.note }), _jsx("p", { className: "font-serif text-sm text-forest/50", children: CATEGORIES[expense.category].name })] })] }), _jsxs("div", { className: "flex items-center gap-4", children: [_jsx("p", { className: "font-mono text-lg text-mauve font-semibold", children: formatCurrency(expense.amount) }), _jsx(motion.button, { whileHover: { scale: 1.1 }, whileTap: { scale: 0.9 }, onClick: () => onDelete(expense.id), className: "p-2 rounded-full bg-rose/10 text-rose opacity-0 group-hover:opacity-100 transition-opacity hover:bg-rose/20", children: _jsx(Trash2, { size: 18 }) })] })] }) }, expense.id))) }) })] }, date))) })) : (_jsx(WatercolorCard, { children: _jsx(EmptyState, { message: "No tales found in your chronicle" }) })), _jsx(BotanicalDivider, {})] }) }));
};
//# sourceMappingURL=ExpenseHistory.js.map